-- funçoes matematicas
-- count mostra tudo qtd total de registros
-- group by mostra quantas coisas o mesmo item esta cadastrado  ex. aluno esta cadastrado em quantos cursos
-- round arredonda , truncate limpa o arredondamento.
--  max pega mairo nota e min menor nota
-- funçoes de grupos      podem ser usadas todas juntas
-- 
-- sub query
--  